### ISSUE TITLE
Dependencies on npm

### ISSUE THREAD

**Issue by CrispyBacon1999** [cjlawson02/ntcore-ts-client#140]
Looks like there's an issue with how you're publishing to npm. None of the dependencies for the project are included (since they're included in the parent package), which is giving me issues when using it on my end.

**Comment by cjlawson02** [comment]
Yeah I reproduced this, will have to fix

**Comment by fisherjacobc** [comment]
Hey there, I think(??) I have found what is causing the issue. I am comparing some files between the last published working tag (0.2.1) and the latest version.

I noticed in the `project.json` file something about dependencies that is in 0.2.1 but not in the latest code:
[0.2.1](https://github.com/cjlawson02/ntcore-ts-client/blob/0.2.1/packages/ntcore-ts-client/project.json#L14C2-L14C2)
[latest](https://github.com/cjlawson02/ntcore-ts-client/blob/beta/packages/ntcore-ts-client/project.json)

**Comment by cjlawson02** [comment]
Hi @CrispyBacon1999 @fisherjacobc can you try https://www.npmjs.com/package/ntcore-ts-client/v/2.0.0-beta.3 please?

Thanks for the help!

**Comment by fisherjacobc** [comment]
according to the published package.json file the dependencies are showing up, so that should fix it, thanks!

https://www.npmjs.com/package/ntcore-ts-client/v/2.0.0-beta.3?activeTab=code
