### ISSUE TITLE
Cached (Key) Attribute Missing

### ISSUE THREAD

**Issue by steve-carpenter** [cjlawson02/ntcore-ts-client#149]
https://github.com/cjlawson02/ntcore-ts-client/blob/196f50d5200fddf874f9164bc42b28bf9a452f76/packages/ntcore-ts-client/src/lib/types/schemas.ts#L45

Network Table spec: https://github.com/wpilibsuite/allwpilib/blob/main/ntcore/doc/networktables4.adoc

Issue:
```
Uncaught ZodError: [
  {
    "code": "unrecognized_keys",
    "keys": [
      "cached"
    ],
    "path": [
      0,
      "params",
      "properties"
    ],
    "message": "Unrecognized key(s) in object: 'cached'"
  }
]
```

**Comment by cjlawson02** [comment]
Thanks for the report!

**Comment by cjlawson02** [comment]
Please try ntcore-ts-client@2.0.0-beta.6 and let me know if this is still an issue. Thanks!
